name: Stellate

on:
  push:
    branches:
      - '**'
# on:
#   workflow_dispatch:
#     inputs:
#       environment:
#         description: 'Environment used for deployment'
#         required: true
#         default: 'staging'
#         type: choice
#         options:
#           - development
#           - staging
#           - production

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: samuelmeuli/action-snapcraft@v1
      - run: sudo snap install dyff yq

      - name: Diff
        run: |
          yq '
            .schema=.environments["dev"].schema
              | .name=.environments["dev"].name
              | .originUrl=.environments["dev"].originUrl
              | del(.environments)
          ' -i new-stellate.yml
          dyff between -b ./new-stellate.yml ./stellate.yml



