name: Update service definition

on:
  push:

env:
  EXTRA_ENV_KEY: FORCE_RESTART
  EXTRA_ENV_VALUE: 233kanfdasfds
  ENVIRONMENT: staging
  APP_NAME: graphql-gateway
  AUTHOR: kareem

jobs:
  update:
    name: Update service
    runs-on: ubuntu-latest
    steps:
      # Wait for previous run to finish to make sure no push conflicts appear
      - name: Wait for previous runs to finish
        uses: mktcode/consecutive-workflow-action@v1
        timeout-minutes: 3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: master #allows for rerun in case of failure
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update service extraEnv
        # if: ${{ github.event.action == 'extra-env' }}
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq -i '.extraEnv += {"name": "$EXTRA_ENV_KEY", "value": "$EXTRA_ENV_VALUE"}' \
              kubernetes/applications/grover-apps/values-$ENVIRONMENT/$APP_NAME.yaml

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git add .
          git commit -m "Automated: $APP_NAME ${{ github.event.action }} in env/pr $ENVIRONMENT by $AUTHOR"
          git rebase origin/master
          git push
