name: Update service definition
on:
  repository_dispatch:
    types:
      # Add/Update extraEnv object inside the given service definition
      #   - If EXTRA_ENV_KEY already exists, it will update it's value with EXTRA_ENV_VALUE
      #   - If EXTRA_ENV_KEY doesn't exist, it will add a new key/value.
      - extra-env

env:
  EXTRA_ENV_KEY: ${{ github.event.client_payload.extra_env_key }}
  EXTRA_ENV_VALUE: ${{ github.event.client_payload.extra_env_value }}
  ENVIRONMENT: ${{ github.event.client_payload.environment }}
  APP_NAME: ${{ github.event.client_payload.app_name }}
  AUTHOR: ${{ github.event.client_payload.author }}

jobs:
  update:
    name: Update service
    runs-on: ubuntu-latest
    steps:
      # Wait for previous run to finish to make sure no push conflicts appear
      - name: Wait for previous runs to finish
        uses: mktcode/consecutive-workflow-action@v1
        timeout-minutes: 3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: master #allows for rerun in case of failure
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update service extraEnv
        # if: ${{ github.event.action == 'extra-env' }}
        uses: mikefarah/yq@master
        env:
          FILE_NAME: kubernetes/applications/grover-apps/values-$ENVIRONMENT/$APP_NAME.yaml
        with:
          cmd: sh .github/workflows/bin/update_extra_env.sh


      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git add .
          git commit -m "Automated: update ${{ github.event.action }} in $APP_NAME for $ENVIRONMENT by $AUTHOR"
          git rebase origin/master
          git push
