name: Stellate

on:
  push:
    branches: [master]
    paths: [stellate.yml]
  pull_request:
    branches: [master]
    paths: [stellate.yml]

permissions:
  # Required for adding PR comment
  pull-requests: write

jobs:
  deploy_development:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set foobar to cool
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.foo.bar = "cool"' 'config.yml'
