name: Stellate

on:
  push:
    branches: [master]
    paths: [stellate.yml]
  pull_request:
    branches: [master]
    paths: [stellate.yml]

permissions:
  # Required for adding PR comment
  pull-requests: write

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.3.0'
          check-latest: true

      - name: Deploy development
        run: |
          npx stellate push --env development
